dist: xenial
language: python
python:
    -  "3.7"

before_install:
    - sudo apt-get install libhdf5-serial-dev
install:
    - pip install -r requirements.txt
    - pip install codecov coverage tables
script:
    - cd tests
    - pytest
    - pytest --cov=stats_can .
