dist: xenial
language: python
python:
    -  "3.7"

install:
    - pip install -r requirements.txt
    - pip install codecov coverage
script:
    - cd tests
    - pytest
    - pytest --cov=stats_can .
